name: CI Push event to GCP

on:
  push:
    branches: dev
    paths:
      - '**meta.json'

jobs:
  diff_and_push_event:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the project front
        run: |
          echo '${{secrets.GOOGLE_CREDENTIALS}}' > google-key.json
          gcloud auth activate-service-account --key-file=./google-key.json
          gcloud config set project ${{secrets.GOOGLE_PROJECT_DEV_ID}}
          commitid=`git log --format="%H" -n 1`
          modified=`git diff-tree --no-commit-id --name-only -r $commitid | grep meta.json`
          for i in $modified; do
            gcloud pubsub topics publish ${{secrets.PUB_SUB_META_TOPIC}} --message "$i"
          done
